name:                ripser-haskell
version:             0.1.0.0
github:              "adamConnerSax/ripser-haskell"
license:             LGPL-3
author:              "Adam Conner-Sax"
maintainer:          "adam_conner_sax@yahoo.com"
copyright:           "2019 Adam Conner-Sax"

extra-source-files:
- Readme.md
- Changelog.md

synopsis:            The slimmest of interfaces to "ripser", a c++ executable for computation of Vietoris-Rips persistence barcodes.
category:            Numeric

description:         Please see the README on GitHub at <https://github.com/adamConnerSax/ripser-haskell#readme>

dependencies:
- arithmoi >= 0.9.0 && < 0.11
- base >= 4.7 && < 5
- bytestring >= 0.10.8 && < 0.11
- data-interval >= 1.0.0 && < 2.1
- foldl >= 1.4.0 && <= 1.5
- hmatrix >= 0.19.0 && < 0.21
- megaparsec >= 7.0 && < 9
- Persistence >= 2.0.1 && < 3
- scientific >= 0.3.6 && < 0.4
- stm >= 2.4.5 && < 2.5.1
- typed-process >= 0.2.5 && < 0.3
- text >= 1.2.2 && < 1.3
- vector >= 0.11.0.0 && < 0.13

library:
  ghc-options:
  - -O
  - -Wall
  source-dirs: src

tests:
  ripser-test:
    main: ripserTest.hs
    source-dirs: test
    ghc-options: -O -Wall
    dependencies:
      - ripser-haskell

